# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/honor/leland/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/honor/leland/proprietary/emui/base/global/ons.bin:system/emui/base/global/ons.bin \
    vendor/honor/leland/proprietary/lib/drm/libdrmhwomavoneplugin.so:system/lib/drm/libdrmhwomavoneplugin.so \
    vendor/honor/leland/proprietary/lib64/drm/libdrmhwomavoneplugin.so:system/lib64/drm/libdrmhwomavoneplugin.so \
    vendor/honor/leland/proprietary/lib64/hw/hw_af_extend.default.so:system/lib64/hw/hw_af_extend.default.so \
    vendor/honor/leland/proprietary/lib/android.hidl.base@1.0.so:system/lib/android.hidl.base@1.0.so \
    vendor/honor/leland/proprietary/lib64/android.hidl.base@1.0.so:system/lib64/android.hidl.base@1.0.so \
    vendor/honor/leland/proprietary/lib64/libc_secshared.so:system/lib64/libc_secshared.so \
    vendor/honor/leland/proprietary/lib/libHidlUtil.so:system/lib/libHidlUtil.so \
    vendor/honor/leland/proprietary/lib64/libHidlUtil.so:system/lib64/libHidlUtil.so \
    vendor/honor/leland/proprietary/lib64/libhuaweicust.so:system/lib64/libhuaweicust.so \
    vendor/honor/leland/proprietary/lib64/libsrsprocessing.so:system/lib64/libsrsprocessing.so \
    vendor/honor/leland/proprietary/lib64/libsws3_1processing.so:system/lib64/libsws3_1processing.so \
    vendor/honor/leland/proprietary/lib64/libsws3processing.so:system/lib64/libsws3processing.so \
    vendor/honor/leland/proprietary/lib64/libsws4processing.so:system/lib64/libsws4processing.so \
    vendor/honor/leland/proprietary/lib/vendor.huawei.hardware.hwfactoryinterface@1.0.so:system/lib/vendor.huawei.hardware.hwfactoryinterface@1.0.so \
    vendor/honor/leland/proprietary/lib64/vendor.huawei.hardware.hwfactoryinterface@1.0.so:system/lib64/vendor.huawei.hardware.hwfactoryinterface@1.0.so
